---
title: "Case Study 4: I can clean your data"
author: "Stacy Wilkerson"
output: 
  html_document:
    code_folding: hide
    keep_md: yes
    theme: cerulean
    fig_width: 12
    fig_height: 8
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mosaic)
library(tidyverse)
library(dplyr)
library(tidyr)
library(openxlsx)
library(stringr)
library(haven)
library(readr)
library(readxl)
library(foreign)
library(plyr)
library(ggrepel)
```

```{r}
heightdatalong.xlsx <- read_xlsx("./heightdatalong.xlsx")
alldata.rds <- read_rds("./alldata.rds")
```

##World Country Plot

```{r, warning=FALSE}
#xlsx plot
germany <- 
  heightdatalong.xlsx %>%
  group_by(Country) %>%
  filter(Country == "Germany")

notgermany <- 
  heightdatalong.xlsx %>%
  group_by(Country) %>%
  filter(Country != "Germany")

ggplot() +
  #geom_line(data = notgermany, mapping = aes(x = year_decade, y = height, group = Country)) +
  geom_point(data = notgermany, mapping = aes(x = year_decade, y = height, group = Country)) +
   geom_line(data = germany, mapping = aes(x = year_decade, y = height, group = Country), color = "red") +
  geom_point(data = germany, mapping = aes(x = year_decade, y = height, group = Country), color = "red", size = 4) +
  theme_bw() +
  labs(x = "Decades", y = "Height (inches)", title = "World Country Height Estimates")
```

##Height Distribution Plot

```{r, warning=FALSE}
#5 data sets plot
alldata.rds %>%
  ggplot(aes(y = height_cm, x = birth_century)) +
  geom_point() + 
  labs(x = "Century of Birth", y = "Height (cm)", title = "Height Distribution Across Centuries") +
  theme_bw()
```





