---
title: "Task 8: Clean and Reformat (aka tidy)"
author: "Stacy Wilkerson"
output: 
  html_document:
    code_folding: hide
    keep_md: yes
    theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mosaic)
library(tidyverse)
library(RColorBrewer)
library(ggrepel)
library(dplyr)
library(tidyr)
library(openxlsx)
library(stringr)
```

###Tidy Data

```{r, message=FALSE, warning=FALSE}
Dart.rds <- read_rds(gzcon(url("https://github.com/byuistats/data/raw/master/Dart_Expert_Dow_6month_anova/Dart_Expert_Dow_6month_anova.RDS")))

tidydata <- Dart.rds %>%
  separate(contest_period, into = c("start", "end"), sep = "-") %>% 
  separate(end, into = c("month_end", "year_end"), sep = -5) %>%
  na.omit

saveRDS(tidydata, "tidydata.rds")
```

###Plot

```{r}
tidydata %>% 
  ggplot() +
  geom_boxplot(mapping = aes(x = year_end, y = value)) + 
  labs(x = "Year", y = "Return Value", title = "Six-Month Returns by Year")
```

###Table

```{r}
DJIAdata <- tidydata %>%
  filter(variable == "DJIA") %>%
  select(month_end, year_end, value) %>%
  spread(key = year_end, value = value)
  
DJIAdata
```






