#In Class Data Challenge Day 8

util <- read_csv("https://byuistats.github.io/M335/data/building_utility_values.csv", 
                 col_types = cols(
                   building_id = col_character(),
                   timestamp = col_datetime(format = "%m%.%d%.%Y %H:%M"),
                   startdate = col_date(format = "%m%.%d%.%Y"),
                   enddate = col_date(format = "%m%.%d%.%Y"),
                   month = col_character(),
                   total_potable_water_gal = col_double(),
                   total_potable_water_costs = col_double(),
                   indoor_potable_water_gal = col_integer(),
                   indoor_potable_water_costs = col_double(),
                   outdoor_water_gal = col_double(),
                   outdoor_water_costs = col_double(),
                   storm_sewer_output_gal = col_character(),
                   storm_sewer_costs = col_double(),
                   electricity_kwh = col_integer(),
                   electricity_costs = col_double(),
                   ren_electricity_kwh = col_integer(),
                   ren_electricity_costs = col_integer(),
                   natural_gas_cubicfeet = col_double(),
                   natural_gas_costs = col_double(),
                   ren_gas_cubicft = col_integer(),
                   ren_gas_costs = col_integer(),
                   fuel_oil_mgal = col_integer(),
                   fuel_oil_costs = col_integer(),
                   steam_mlb = col_double(),
                   steam_costs = col_double(),
                   chilled_water_ton_hr = col_integer(),
                   chilled_water_costs = col_integer(),
                   fuel_coal_ton = col_integer(),
                   fuel_coal_costs = col_integer(),
                   source_energy_coal_percent = col_double(),
                   source_energy_coal_efficiency = col_character(),
                   source_energy_fuel_oil_percent = col_character(),
                   source_energy_fuel_oil_efficiency = col_character(),
                   source_energy_natural_gas_percent = col_character(),
                   source_energy_natural_gas_efficiency = col_character(),
                   source_energy_propane_percent = col_character(),
                   source_energy_propane_efficiency = col_character(),
                   source_energy_hydro_percent = col_double(),
                   source_energy_hydro_efficiency = col_character(),
                   source_energy_wind_percent = col_double(),
                   source_energy_wind_efficiency = col_character(),
                   source_energy_geothermal_percent = col_character(),
                   source_energy_geothermal_efficiency = col_character(),
                   source_energy_low_impact_hydro_percent = col_character(),
                   source_energy_low_impact_hydro_efficiency = col_character(),
                   source_energy_other_percent = col_double(),
                   source_energy_other_efficiency = col_character(),
                   peak_electricity_demand_kW = col_double(),
                   peak_demand_costs = col_double(),
                   maintenance_contract_cost = col_double(),
                   maintenance_additional_cost = col_double(),
                   number_maintenance_requests = col_integer(),
                   number_preventative_jobs = col_integer(),
                   buildingkg_hazardous_chemicals_used = col_character(),
                   housekeeping_maintenance_costs = col_double(),
                   housekeeping_kg_hazardous_waste_used = col_character(),
                   grounds_maintenance_costs = col_double(),
                   grounds_kg_hazardous_chemicals_used = col_integer(),
                   solid_sanitary_waste_cubicyards = col_double(),
                   solid_sanitary_waste_costs = col_double(),
                   hazardous_waste_generated_gal = col_character(),
                   hazardous_waste_costs = col_character(),
                   recycled_plastic_ft3 = col_character(),
                   recycled_plastic_cost = col_character(),
                   recycled_cardboard_ft3 = col_character(),
                   recycled_cardboard_cost = col_character(),
                   recycled_metal_ft3 = col_character(),
                   recycled_metal_cost = col_character(),
                   recycled_paper_ft3 = col_double(),
                   recycled_paper_cost = col_double(),
                   recycled_glass_ft3 = col_character(),
                   recycled_glass_cost = col_character(),
                   parking_leased_costs = col_double(),
                   number_leased_parking_spaces = col_double(),
                   recycled_plastic_lbs = col_character(),
                   recycled_cardboard_lbs = col_integer(),
                   recycled_metal_lbs = col_integer(),
                   recycled_paper_lbs = col_double(),
                   recycled_glass_lbs = col_character(),
                   steam_pressure_psig = col_character(),
                   chilled_water_delta_degF = col_character(),
                   solid_sanitary_waste_lbs = col_double(),
                   recycled_total_ft3 = col_character(),
                   preventative_jobs_hours = col_double(),
                   maintenance_request_hours = col_double(),
                   electric_MBTU = col_double(),
                   naturalgas_MBTU = col_double(),
                   steam_MBTU = col_double(),
                   chilledwater_MBTU = col_double()
                 ))

tidyutil <- util %>% 
  select(building_id, timestamp, startdate, enddate, month, contains("water")) %>% 
  separate(building_id, c("state", "ID"), 2) %>%
  separate(enddate, c("year", "month", "day"), sep = "-", remove = FALSE)



